name: 'Update Angular Action'
on:
  schedule:
    - cron: '30 5 * * 3' # Every Wednesday at 5:30 AM

jobs:
  ngxUptodate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Updating ng dependencies'
        uses: fast-facts/ng-update@v1
        with:
          base-branch: 'master'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
